source 'https://github.com/CocoaPods/Specs.git'

target 'ROFilterSort', :exclusive => true do
  pod "ROFilterSort", :path => "../"
  pod "ROCardToss"
end

target 'Tests', :exclusive => true do
  pod "ROFilterSort", :path => "../"

  
end
